# Generated by Django 4.2 on 2023-04-09 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_favourite_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_item', to='main.items')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_Item', to='buyitems.item_purchased')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
