# Generated by Django 4.2 on 2023-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_favourite_options'),
        ('buyitems', '0004_alter_purchased_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_purchased',
            name='item',
        ),
        migrations.AddField(
            model_name='item_purchased',
            name='item',
            field=models.ManyToManyField(related_name='purchased_item', to='main.items'),
        ),
    ]
