# Generated by Django 4.2 on 2023-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_favourite_options'),
        ('buyitems', '0005_remove_item_purchased_item_item_purchased_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='purchased_Item', to='main.items'),
        ),
        migrations.DeleteModel(
            name='Item_Purchased',
        ),
    ]
