# Generated by Django 4.2 on 2023-04-07 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('item_slug', models.SlugField(default=uuid.uuid1, editable=False, unique=True)),
                ('category', models.ManyToManyField(related_name='category', to='main.category')),
                ('reviews', models.ManyToManyField(related_name='review', to='main.review')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='item',
            field=models.ManyToManyField(related_name='items', to='main.items'),
        ),
    ]
