# Generated by Django 4.2 on 2023-04-08 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_items_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
