# Generated by Django 4.2 on 2023-04-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_favourite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='main.category'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='Favourite_restaurants', to='main.restaurants'),
        ),
    ]
