# Generated by Django 4.2 on 2023-04-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_favourite_favourite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourite'},
        ),
    ]
