# Generated by Django 4.2 on 2023-04-14 04:31

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_favourite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=main.models.user_directory_path, verbose_name='item_picture'),
            preserve_default=False,
        ),
    ]
