# Generated by Django 4.2 on 2023-04-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
    ]
