# Generated by Django 4.2 on 2023-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
